baseURL = "https://packetcrafter.github.io"
languageCode = "en-us"
title = "Network DevOps by Isaias Luna"

# Tell Hugo to use the new theme
theme = "terminal" 

# --- Required for Syntax Highlighting ---
[markup.highlight]
noClasses = false

# --- Optional Theme Parameters (Recommended) ---
[params]
    # Terminal theme options:
  themeColor = "orange"         # choices: orange, blue, red, green, pink, yellow
  fullWidthTheme = false
  centerTheme = true
  readingTime = true
  Toc = true
  TocTitle = "Table of Contents"

[params.logo]
  logoText = "Isaias / NetDevOps"
  logoHomeLink = "/"

# --- MENU ---
[[menu.main]]
  identifier = "posts"
  name = "Posts"
  url = "/posts/"
  weight = 1

[[menu.main]]
  identifier = "about"
  name = "About"
  url = "/about/"
  weight = 2
